version: '3.8'
services:
  nginx:
    image: ghcr.io/sfidanza/worldcup-frontend
    ports:
      - "8090:80"

  app:
    image: ghcr.io/sfidanza/worldcup-backend
    environment:
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
      - MONGO_USER
      - MONGO_PWD
      - MONGO_DB=worldcup2014
      - NODE_PORT=9090
      - COOKIE_SEED
      - AUTH_CLIENT_ID
      - AUTH_CLIENT_SECRET
      - AUTH_REDIRECT_URL

  mongo:
    image: mongo:4-focal  # MongoDB 5.0+ requires a CPU with AVX support. Does not run in production!
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PWD
      - MONGO_INITDB_DATABASE=worldcup2014
    volumes:
      - mongodb:/data/db
      - ./database/initdb-start:/docker-entrypoint-initdb.d

volumes:
  mongodb:
