services:
  nginx:
    build: ./client
    ports:
      - "8090:80"
    volumes:
      - client_target:/var/www/worldcup

  build:
    build:
      context: ./client
      target: build
    volumes:
      - ./client:/usr/src/app
      - client_target:/usr/src/app/target
      - client_node_modules:/usr/src/app/node_modules
    command: node --run debug

  app:
    build: ./server
    volumes:
      - ./server:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - "9229:9229"
    command: node --run debug
  
  admin:
    image: mongo-express:1.0.2-20
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://$MONGO_USER:$MONGO_PWD@mongo:27017
      - ME_CONFIG_BASICAUTH_USERNAME
      - ME_CONFIG_BASICAUTH_PASSWORD
    ports:
      - "8091:8081"

  e2e:
    build: ./e2e
    ports:
      - "9323:9323"
    volumes:
      - ./e2e:/usr/src/app
      - e2e_node_modules:/usr/src/app/node_modules
    stdin_open: true
    tty: true

volumes:
  node_modules:
  client_node_modules:
  client_target:
  e2e_node_modules:
