version: '3'
services:
  nginx:
    build: client/
    ports:
      - "8090:80"
    depends_on:
      - app

  app:
    build: server/
    environment:
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
      - MONGO_USER
      - MONGO_PWD
      - MONGO_DB=worldcup2014
      - NODE_PORT=9090
      - COOKIE_SEED
      - AUTH_CLIENT_ID
      - AUTH_CLIENT_SECRET
      - AUTH_REDIRECT_URL
    expose:
      - "9090"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2.8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PWD
      - MONGO_INITDB_DATABASE=worldcup2014
    volumes:
      - mongodb:/data/db
      - ./docker/mongo/initdb-start:/docker-entrypoint-initdb.d
    expose:
      - "27017"
  
volumes:
  mongodb:
  app-statics:
