version: '3.8'
services:
  nginx:
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.worldcup.rule=Host(`$HOST`)
        - traefik.http.services.worldcup.loadbalancer.server.port=80
        # Activate https
        - traefik.http.routers.worldcup.tls=true
        - traefik.http.routers.worldcup.tls.certresolver=myresolver
        - traefik.http.routers.worldcup.middlewares=security@file
    networks:
      - gateway
      - default

  # admin:
  #   deploy:
  #     labels:
  #       - traefik.enable=true
  #       - traefik.http.routers.worldcup-admin.rule=Host(`$HOST_ADMIN`)
  #       - traefik.http.services.worldcup-admin.loadbalancer.server.port=8081
  #       # Activate https
  #       - traefik.http.routers.worldcup-admin.tls=true
  #       - traefik.http.routers.worldcup-admin.tls.certresolver=myresolver
  #       - traefik.http.routers.worldcup-admin.middlewares=security@file
  #   networks:
  #     - gateway
  #     - default

networks:
  gateway:
    external: true
    name: gateway