version: '3'
services:
  nginx:
    build: client/
    # volumes:
    #   - ./client/target:/var/www/worldcup2014
    #   - ./client:/usr/src/app
    #   - client_node_modules:/usr/src/app/node_modules
    # tty: true

  app:
    build: server/
    volumes:
      - ./server:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - "9229:9229"
    command: npm run debug
  
  admin:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_PWD
    ports:
      - "8091:8081"
    depends_on:
      - mongo

volumes:
  node_modules:
  # client_node_modules:
