version: '3'
services:
  nginx:
    build: docker/nginx
    volumes:
      - ./target:/var/www/worldcup2014
    ports:
      - "8090:80"
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile-DEV
    environment:
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
      - MONGO_USER
      - MONGO_PWD
      - MONGO_DB=worldcup2014
      - NODE_PORT=9090
    volumes:
      - .:/usr/src/app
    # ports:
    #   - "9090:9090"
    expose:
      - "9090"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2.8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PWD
      - MONGO_INITDB_DATABASE=worldcup2014
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
      - ./docker/mongo/initdb-start:/docker-entrypoint-initdb.d
    expose:
      - "27017"

  admin:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_PWD
    ports:
      - "8091:8081"
    depends_on:
      - mongo
  
volumes:
  mongodb:
  mongodb_config:
