version: '3.8'
services:
  nginx:
    build: ./client
    volumes:
      - client_target:/var/www/worldcup2014
    restart: "no"

  build:
    build:
      context: ./client
      target: build
    volumes:
      - ./client:/usr/src/app
      - client_target:/usr/src/app/target
      - client_node_modules:/usr/src/app/node_modules
    command: npm run debug

  app:
    build: ./server
    volumes:
      - ./server:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - "9229:9229"
    command: npm run debug
    restart: "no"
  
  mongo:
    restart: "no"
    
  admin:
    image: mongo-express:0.54
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_PWD
    ports:
      - "8091:8081"
    depends_on:
      - mongo

volumes:
  node_modules:
  client_node_modules:
  client_target:
