apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "names.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "names.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    helm.sh/chart: {{ include "names.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "names.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "names.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.Version }}
        helm.sh/chart: {{ include "names.chart" . }}
    spec:
      containers:
        - name: worldcup-frontend
          image: "ghcr.io/sfidanza/worldcup-frontend:{{ .Values.worldcup.image.tag }}"
          imagePullPolicy: {{ .Values.worldcup.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: NODE_HOSTNAME
              value: localhost
            - name: NODE_PORT
              value: "9090"

        - name: worldcup-backend
          image: "ghcr.io/sfidanza/worldcup-backend:{{ .Values.worldcup.image.tag }}"
          imagePullPolicy: {{ .Values.worldcup.image.pullPolicy }}
          ports:
            - name: node
              containerPort: 9090
              protocol: TCP
          env:
            - name: MONGO_HOSTNAME
              value: localhost
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: db-user
                  key: username
            - name: MONGO_PWD
              valueFrom:
                secretKeyRef:
                  name: db-user
                  key: password
            - name: NODE_PORT
              value: "9090"
            - name: AUTH_REDIRECT_URL
              value: "{{ .Values.worldcup.authRedirectUrl }}"
          envFrom:
            - secretRef:
                name: backend

        - name: mongo
          image: "mongo:{{ .Values.mongo.image.tag }}"
          imagePullPolicy: {{ .Values.mongo.image.pullPolicy }}
          ports:
            - name: mongo
              containerPort: 27027
              protocol: TCP
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-user
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-user
                  key: password
            - name: MONGO_INITDB_DATABASE
              value: worldcup-users
          envFrom:
            - secretRef:
                name: worldcup-admin
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d

      volumes:
        - name: mongodb-data
          hostPath: # should be a local PV
            path: {{ .Values.mongo.data }}
            type: DirectoryOrCreate
        - name: initdb
          configMap:
            name: worldcup-initdb

{{- with .Values.nodeSelector }} # needed on a multi-node cluster due to the hostPath volume for db-data
      nodeSelector:
        {{- toYaml . | nindent 8 }}
{{- end }}
