apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "names.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "names.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    helm.sh/chart: {{ include "names.chart" . }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host("{{ .Values.route.host }}") && PathPrefix("{{ .Values.route.path.frontend }}")
      services:
        - name: {{ include "names.fullname" . }}
          port: frontend
    - kind: Rule
      match: Host("{{ .Values.route.host }}") && PathPrefix("{{ .Values.route.path.backend }}")
      services:
        - name: {{ include "names.fullname" . }}
          port: backend
