apiVersion: v1
kind: Service
metadata:
  name: {{ include "names.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "names.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    helm.sh/chart: {{ include "names.chart" . }}
spec:
  type: ClusterIP
  ports:
    - name: frontend
      port: 8080
      protocol: TCP
      targetPort: http
    - name: backend
      port: 9090
      protocol: TCP
      targetPort: node
  selector:
    app.kubernetes.io/name: {{ include "names.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
