apiVersion: v1
kind: Service
metadata:
  name: {{ include "worldcup.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "worldcup.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ include "worldcup.chart" . }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "worldcup.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
